import frappe

frappe.db.sql("UPDATE `tabApplication Usage log` SET url = current_url WHERE current_url IS NOT NULL AND current_url != ''")
frappe.db.sql("UPDATE `tabApplication Usage log` SET process_name = process_id WHERE process_id IS NOT NULL AND process_id != ''")
frappe.db.sql("UPDATE `tabApplication Usage log` SET from_time = CAST(from_time AS DATETIME)")
frappe.db.sql("UPDATE `tabApplication Usage log` SET to_time = CAST(to_time AS DATETIME)")
frappe.db.sql("UPDATE `tabApplication Usage log` SET duration = TIMESTAMPDIFF(SECOND, from_time, to_time)")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET from_time = start_time WHERE start_time IS NOT NULL")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET to_time = end_time WHERE end_time IS NOT NULL")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET from_time = CAST(from_time AS DATETIME)")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET to_time = CAST(to_time AS DATETIME)")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET duration = TIMESTAMPDIFF(SECOND, from_time, to_time)")
frappe.db.sql("UPDATE `tabEmployee Idle Time` SET date = CAST(from_time AS DATE)")
frappe.db.sql("UPDATE `tabWork Intensity` SET time = date_time WHERE date_time IS NOT NULL")
frappe.db.sql("UPDATE `tabWork Intensity` SET time = CAST(time AS DATETIME)")
frappe.db.sql("UPDATE `tabWork Intensity` SET key_strokes = total_keystrokes")
frappe.db.sql("UPDATE `tabWork Intensity` SET mouse_clicks = total_mouse_clicks")
frappe.db.sql("UPDATE `tabWork Intensity` SET mouse_scrolls = total_scroll")
frappe.db.sql("UPDATE `tabScreen Screenshot Log` SET time = datetime WHERE datetime IS NOT NULL")
frappe.db.sql("UPDATE `tabScreen Screenshot Log` SET time = CAST(time AS DATETIME)")
